### ISSUE TITLE
Where Is The Image Saved

### ISSUE THREAD

**Issue by maxexcloo** [pikvm/os#3]
I'm attempting to build an image on a cloud VM, it all seems to be working and I don't see any errors but after it's complete I'm not sure where it's actually saved the output - could you assist?

**Comment by mdevaev** [comment]
Hello! After the build, the image is stored in docker storage. You can extract it using the `make image` command. After that see `images` directory in the os buildroot.

**Comment by maxexcloo** [comment]
Thank you 👍
